name:                kabu
version:             0.1.0.0
github:              "osak/kabu"
license:             AGPL-3.0-or-later
author:              "Osamu Koga (osa_k)"
maintainer:          "osak.63@gmail.com"
copyright:           "2020 Osamu Koga"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            App category here

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/osak/kabu#readme>

dependencies:
- base >= 4.7 && < 5
- text
- yaml
- unordered-containers

library:
  source-dirs: src

executables:
  kabu-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - kabu

tests:
  kabu-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - kabu
